const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');

/**
 * Generate Daily Cause List PDF directly into a streaming response or Buffer.
 * Never persists to disk (No document storage).
 */
const generateCauseListPDF = (hearings, firm, dateStr, res) => {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `inline; filename="Cause_List_${dateStr}.pdf"`);

  doc.pipe(res);

  // Header banner
  doc.rect(40, 40, 515, 60).fill('#0A1128');
  doc.fillColor('#FFFFFF').fontSize(18).font('Helvetica-Bold').text(firm.name || 'Advocate DigiDiary', 55, 52);
  doc.fontSize(10).font('Helvetica').fillColor('#C59B27').text(`DAILY CAUSE LIST & COURT ROSTER — ${dateStr}`, 55, 75);
  doc.fontSize(9).fillColor('#E2E8F0').text(`Bar Enr: ${firm.barCouncilRegistration || 'N/A'} | ${firm.chamberNumber || ''}`, 360, 75, { align: 'right' });

  doc.moveDown(3);

  if (!hearings || hearings.length === 0) {
    doc.fillColor('#46464D').fontSize(12).font('Helvetica').text('No hearings listed for this date.', 55, 130);
    doc.end();
    return;
  }

  let y = 120;

  hearings.forEach((h, index) => {
    if (y > 720) {
      doc.addPage();
      y = 50;
    }

    // Hearing Item Card
    doc.rect(40, y, 515, 80).fillAndStroke('#F8FAFC', '#E2E8F0');
    // Accent gold status bar
    doc.rect(40, y, 4, 80).fill('#C59B27');

    doc.fillColor('#0A1128').fontSize(11).font('Helvetica-Bold').text(`${index + 1}. ${h.caseId ? h.caseId.title : 'Matter'}`, 52, y + 10);
    doc.fillColor('#46464D').fontSize(9).font('Helvetica').text(`Suit/Case No: ${h.caseId ? h.caseId.caseNumber : 'N/A'} | CNR: ${h.caseId ? (h.caseId.cnrNumber || 'N/A') : 'N/A'}`, 52, y + 25);
    doc.fillColor('#0A1128').fontSize(9).font('Helvetica').text(`Court: ${h.court} — ${h.courtroom || 'Courtroom'} | Presiding: ${h.judge || 'Hon. Judge'}`, 52, y + 40);
    doc.fillColor('#997A1E').fontSize(9).font('Helvetica-Bold').text(`Stage: ${h.purpose} | Time: ${h.time || '10:00 AM'} | Status: ${h.status}`, 52, y + 55);

    if (h.benchNotes) {
      doc.fillColor('#64748B').fontSize(8).font('Helvetica-Oblique').text(`Note: ${h.benchNotes}`, 52, y + 68, { width: 490, height: 10, ellipsis: true });
    }

    y += 90;
  });

  // Footer
  doc.fontSize(8).fillColor('#94A3B8').text(
    `Generated by Advocate DigiDiary Practice Platform on ${new Date().toLocaleString()} | Confidential Chamber Record`,
    40,
    780,
    { align: 'center', width: 515 }
  );

  doc.end();
};

/**
 * Generate Fee Statement / Ledger in Excel format.
 * Streamed directly as application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.
 */
const generateFeeLedgerExcel = async (payments, firm, res) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = firm.name || 'Advocate DigiDiary';
  workbook.created = new Date();

  const worksheet = workbook.addWorksheet('Fee Ledger');

  worksheet.columns = [
    { header: 'Receipt No.', key: 'receiptNumber', width: 18 },
    { header: 'Date', key: 'paymentDate', width: 15 },
    { header: 'Client', key: 'clientName', width: 25 },
    { header: 'Case / Matter', key: 'caseTitle', width: 30 },
    { header: 'Particulars / Scope', key: 'description', width: 35 },
    { header: 'Fee Head', key: 'category', width: 22 },
    { header: 'Mode', key: 'paymentMethod', width: 12 },
    { header: 'Reference', key: 'transactionReference', width: 20 },
    { header: 'Amount (INR)', key: 'amount', width: 18 },
    { header: 'Status', key: 'status', width: 14 },
  ];

  // Style header row
  worksheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  worksheet.getRow(1).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF0A1128' }, // Sovereign Navy
  };

  payments.forEach((p) => {
    worksheet.addRow({
      receiptNumber: p.receiptNumber,
      paymentDate: new Date(p.paymentDate).toLocaleDateString(),
      clientName: p.clientId ? p.clientId.name : 'N/A',
      caseTitle: p.caseId ? p.caseId.title : 'General Retainer',
      description: p.description || 'Professional Legal Fee',
      category: p.category,
      paymentMethod: p.paymentMethod,
      transactionReference: p.transactionReference || '-',
      amount: p.amount,
      status: p.status,
    });
  });

  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.setHeader('Content-Disposition', `attachment; filename="Chamber_Fee_Ledger.xlsx"`);

  await workbook.xlsx.write(res);
  res.end();
};

/**
 * Generate Cases Summary in Excel format.
 */
const generateCasesExcel = async (cases, firm, res) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = firm.name || 'Advocate DigiDiary';
  workbook.created = new Date();

  const worksheet = workbook.addWorksheet('Cases Portfolio');

  worksheet.columns = [
    { header: 'Case Number', key: 'caseNumber', width: 20 },
    { header: 'CNR Number', key: 'cnrNumber', width: 22 },
    { header: 'Case Title', key: 'title', width: 35 },
    { header: 'Client', key: 'clientName', width: 25 },
    { header: 'Representation', key: 'partyRole', width: 16 },
    { header: 'Court / Forum', key: 'court', width: 25 },
    { header: 'Courtroom', key: 'courtroom', width: 15 },
    { header: 'Current Stage', key: 'stage', width: 20 },
    { header: 'Status', key: 'status', width: 15 },
    { header: 'Current Hearing', key: 'currentHearingDate', width: 16 },
    { header: 'Agreed Fee (INR)', key: 'totalAgreedFee', width: 18 },
  ];

  worksheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  worksheet.getRow(1).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF0A1128' },
  };

  cases.forEach((c) => {
    worksheet.addRow({
      caseNumber: c.caseNumber,
      cnrNumber: c.cnrNumber || 'N/A',
      title: c.title,
      clientName: c.clientId ? c.clientId.name : 'N/A',
      partyRole: c.partyRole || c.clientRepresentation || 'Petitioner',
      court: c.court,
      courtroom: c.courtRoom || c.courtroom || 'N/A',
      stage: c.stage || c.currentStage || 'Hearing',
      status: c.status,
      currentHearingDate: c.currentHearingDate ? new Date(c.currentHearingDate).toLocaleDateString() : 'N/A',
      totalAgreedFee: c.totalAgreedFee || c.agreedFee || 0,
    });
  });

  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.setHeader('Content-Disposition', 'attachment; filename="Case_Portfolio_Export.xlsx"');

  await workbook.xlsx.write(res);
  res.end();
};

/**
 * Generate Expenses Summary in Excel format.
 */
const generateExpensesExcel = async (expenses, firm, res) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = firm.name || 'Advocate DigiDiary';
  workbook.created = new Date();

  const worksheet = workbook.addWorksheet('Disbursements');

  worksheet.columns = [
    { header: 'Date', key: 'expenseDate', width: 15 },
    { header: 'Category', key: 'category', width: 20 },
    { header: 'Description', key: 'description', width: 35 },
    { header: 'Case / Matter', key: 'caseDetails', width: 30 },
    { header: 'Amount (INR)', key: 'amount', width: 18 },
    { header: 'Billable', key: 'isBillable', width: 12 },
    { header: 'Receipt / Ref #', key: 'receiptNumber', width: 20 },
  ];

  worksheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  worksheet.getRow(1).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF0A1128' },
  };

  expenses.forEach((e) => {
    worksheet.addRow({
      expenseDate: new Date(e.expenseDate).toLocaleDateString(),
      category: e.category,
      description: e.description,
      caseDetails: e.caseId ? `${e.caseId.caseNumber} - ${e.caseId.title}` : 'General Chamber',
      amount: e.amount,
      isBillable: e.isBillable ? 'Yes' : 'No',
      receiptNumber: e.receiptNumber || e.billNumber || '-',
    });
  });

  res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
  res.setHeader('Content-Disposition', 'attachment; filename="Expenses_Ledger.xlsx"');

  await workbook.xlsx.write(res);
  res.end();
};

/**
 * Generate generic CSV string from array of objects and fields.
 */
const generateCSV = (data, fields) => {
  const headers = fields.map((f) => `"${f.label}"`).join(',');
  const rows = data.map((item) => {
    return fields
      .map((f) => {
        let val = typeof f.value === 'function' ? f.value(item) : item[f.value];
        if (val === null || val === undefined) val = '';
        val = String(val).replace(/"/g, '""');
        return `"${val}"`;
      })
      .join(',');
  });

  return [headers, ...rows].join('\n');
};

module.exports = {
  generateCauseListPDF,
  generateFeeLedgerExcel,
  generateCasesExcel,
  generateExpensesExcel,
  generateCSV,
};


